/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.garen.mc.swagger.api;


import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import org.garen.mc.swagger.model.ErrorModel;
import org.garen.mc.swagger.model.SuccessModel;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-09-15T06:44:56.262Z")

@Api(value = "partnerLinks", description = "the partnerLinks API")
public interface PartnerLinksApi {

    @ApiOperation(value = "获取合作链接列表", notes = "获取合作链接列表 ", response = SuccessModel.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful response", response = SuccessModel.class),
        @ApiResponse(code = 200, message = "unexpected error", response = ErrorModel.class) })
    
    @RequestMapping(value = "/partnerLinks",
        method = RequestMethod.GET)
    ResponseEntity<SuccessModel> getpartnerLinks();

}
