# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "1.0.0"
  title: 文章评论接口

#host: 127.0.0.1:7443
#basePath: /v1
#schemes:
#  - https
#produces:
#  - application/json
#consumes:
#  - application/json

# Describe your paths here
paths:
  /comments:
    post:
      summary: 新增文章评论
      description: |
        新增文章评论
      operationId: saveComment
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: comment
          description: 文章评论
          schema:
            $ref: '#/definitions/comment'
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/responseModel'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
      tags:
        - comment
  /comments/{id}:
    delete:
      tags:
        - comment
      summary: id删除
      description: |
        根据id删除文章评论
      operationId: deleteComment
      parameters:
        - name: id
          in: path
          description: id
          format: int64
          type: integer
          required: true
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/responseModel'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
  /comments/page:
    get:
      tags:
        - comment
      summary: 文章编码分页查询
      description: |
        根据文章编码分页查询文章评论
      operationId: getByPage
      parameters:
        - name: articleCode
          in: query
          description: 文章编码
          type: string
        - name: start
          in: query
          description: 分页开始索引
          type: integer
          format: int32
        - name: length
          in: query
          description: 每页数量
          type: integer
          format: int32
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/responseModel'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  comment:
    type: object
    properties:
      content:
        type: string
        maxLength: 100
        description: 评论内容
      articleCode:
        type: string
        maxLength: 64
        description: 文章编码
  responseModel:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      data:
        type: string
  errorModel:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /garen.org/oss/1.0.0
schemes:
 - https
 - http