mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: org.garen.operation.mybatis.mapper
  type-handlers-package: org.apache.ibatis.type.LocalDateTypeHandler

spring:
#  datasource:
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://172.24.133.35:3306/puhui_operation?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
#      username: puhui_operation
#      password: puhui_operation
#      type: com.zaxxer.hikari.HikariDataSource
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.104.170.186:3306/mc?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 7Tf88ga2pU
      type: com.zaxxer.hikari.HikariDataSource
  redis:
      database: 0
      host: localhost
      port: 6379
      password:
      timeout: 6000
      key:
        menu: menuCache_parentCode_0
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
server:
  port: 9093
  tomcat:
    max-threads: 1024
    uri-encoding: utf-8
    basedir: /home/tomcat-mc

