package org.garen.mc.remote.dto;

import java.util.Date;

public class App {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.id
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.app_code
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    private String appCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.app_name
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    private String appName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.permission
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    private Boolean permission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.create_time
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.update_time
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.id
     *
     * @return the value of app.id
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.id
     *
     * @param id the value for app.id
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.app_code
     *
     * @return the value of app.app_code
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.app_code
     *
     * @param appCode the value for app.app_code
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.app_name
     *
     * @return the value of app.app_name
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.app_name
     *
     * @param appName the value for app.app_name
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    public void setAppName(String appName) {
        this.appName = appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.permission
     *
     * @return the value of app.permission
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    public Boolean getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.permission
     *
     * @param permission the value for app.permission
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    public void setPermission(Boolean permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.create_time
     *
     * @return the value of app.create_time
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.create_time
     *
     * @param createTime the value for app.create_time
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.update_time
     *
     * @return the value of app.update_time
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.update_time
     *
     * @param updateTime the value for app.update_time
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}