package org.garen.mc.remote.dto;

import java.util.Date;

public class Login {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.id
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.login_name
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.password
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.user_code
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.create_time
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.id
     *
     * @return the value of login.id
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.id
     *
     * @param id the value for login.id
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.login_name
     *
     * @return the value of login.login_name
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.login_name
     *
     * @param loginName the value for login.login_name
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.password
     *
     * @return the value of login.password
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.password
     *
     * @param password the value for login.password
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.user_code
     *
     * @return the value of login.user_code
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.user_code
     *
     * @param userCode the value for login.user_code
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.create_time
     *
     * @return the value of login.create_time
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.create_time
     *
     * @param createTime the value for login.create_time
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}